//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MdNoteToGithub.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MdNoteToGithub.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚙️ Your bot&apos;s settings:.
        /// </summary>
        internal static string BotSettings {
            get {
                return ResourceManager.GetString("BotSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🖼 Download photo:.
        /// </summary>
        internal static string DownloadImages {
            get {
                return ResourceManager.GetString("DownloadImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ Error: Repository not found. Check the owner&apos;s name, repository name, and token permissions..
        /// </summary>
        internal static string ErrorGithubNotFound {
            get {
                return ResourceManager.GetString("ErrorGithubNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ Incorrect format. Use: /register TOKEN Owner/Repo`.
        /// </summary>
        internal static string ErrorInvalidRegistrationFormat {
            get {
                return ResourceManager.GetString("ErrorInvalidRegistrationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ Error: Invalid or expired GitHub token..
        /// </summary>
        internal static string ErrorInvalidToken {
            get {
                return ResourceManager.GetString("ErrorInvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ An error occurred. Please try again later..
        /// </summary>
        internal static string ErrorSendMessage {
            get {
                return ResourceManager.GetString("ErrorSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForwardedFrom.
        /// </summary>
        internal static string ForwardedFrom {
            get {
                return ResourceManager.GetString("ForwardedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🌐 Language:.
        /// </summary>
        internal static string InfoLanguage {
            get {
                return ResourceManager.GetString("InfoLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language of the messages has been changed.
        /// </summary>
        internal static string InfoLanguageChanged {
            get {
                return ResourceManager.GetString("InfoLanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ The note has been saved to the Inbox folder!.
        /// </summary>
        internal static string InfoNoteCreated {
            get {
                return ResourceManager.GetString("InfoNoteCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ First, sign up using the /register command..
        /// </summary>
        internal static string InfoRegistration {
            get {
                return ResourceManager.GetString("InfoRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ Off.
        /// </summary>
        internal static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ On.
        /// </summary>
        internal static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        internal static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings have been updated!.
        /// </summary>
        internal static string SettingsUpdated {
            get {
                return ResourceManager.GetString("SettingsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi! I&apos;m a bot for saving notes on GitHub.
        ///To get started, register your repository with the following command:
        /// /register YOUR-GITHUB-TOKEN Owner/Repository
        ///
        ///Example:
        /// /register githubpat12345 MyUsername/MyObsidianVault
        ///
        ///Instructions for obtaining a token:
        ///1) Token generation page: https://github.com/settings/personal-access-tokens/new
        ///2) Enter a token name (Token name)
        ///3) Select the token&apos;s expiration date (Expiration)
        ///4) Select the repository (Repository access -&gt; Only select repositories)
        ///5) Gr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
