//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObsidianTgBot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ObsidianTgBot.Resources.Strings.ru", typeof(Strings_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ Ошибка: Репозиторий не найден. Проверь имя владельца, название репозитория и права токена..
        /// </summary>
        internal static string ErrorGithubNotFound {
            get {
                return ResourceManager.GetString("ErrorGithubNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ Неверный формат. Используй: /register ТОКЕН Owner/Repo`.
        /// </summary>
        internal static string ErrorInvalidRegistrationFormat {
            get {
                return ResourceManager.GetString("ErrorInvalidRegistrationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ Ошибка: Неверный или просроченный GitHub токен..
        /// </summary>
        internal static string ErrorInvalidToken {
            get {
                return ResourceManager.GetString("ErrorInvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ Произошла ошибка. Попробуй позже..
        /// </summary>
        internal static string ErrorSendMessage {
            get {
                return ResourceManager.GetString("ErrorSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переслано из
        ///.
        /// </summary>
        internal static string ForwardedFrom {
            get {
                return ResourceManager.GetString("ForwardedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык сообщений изменен.
        /// </summary>
        internal static string InfoLanguageChanged {
            get {
                return ResourceManager.GetString("InfoLanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ Заметка сохранена в папку Inbox!.
        /// </summary>
        internal static string InfoNoteCreated {
            get {
                return ResourceManager.GetString("InfoNoteCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ Сначала зарегистрируйся с помощью команды /register..
        /// </summary>
        internal static string InfoRegistration {
            get {
                return ResourceManager.GetString("InfoRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Источник.
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет! Я бот для сохранения заметок в GitHub.
        ///Чтобы начать, зарегистрируй свой репозиторий командой:
        /// /register ТВОЙ_GITHUB_TOKEN Владелец/Репозиторий
        ///
        ///Пример:
        /// /register github_pat_12345 MyUsername/MyObsidianVault
        ///
        ///Инструкция получения токена: 
        ///1) Станица генерации токенов: https://github.com/settings/personal-access-tokens/new
        ///2) Ввести название токена (Token name)
        ///3) Выбрать срок действия токена (Expiration)
        ///4) Выбрать репозиторий (Repository access -&gt; Only select repositories)
        ///5) Выдать права [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
